version: "3.1"

services:

  db:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    environment:     
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"      
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:3.0-alpine"
    ports:
      - "16379:6379"
    depends_on:
      - db  
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "32769:80"
    depends_on:
      - redis      

volumes:
  pgdata:
    driver: local